language: rust
rust:
  - nightly
  - 1.0.0-beta.4
install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update
  - sudo apt-get install -y libXxf86vm-dev libvpx-dev
script: cargo build --verbose
notifications:
  email:
    on_success: never
